In this branch I build a webiste for remote course
MohammedElseddik/HTML-CSS-JavaScript-capstone-project pull request #1
Opened 2022-03-10 18:09 UTC by MohammedElseddik

## In this branch I : 
- created my first capstone project, the website is about remote jobs and how people can work remotely.
- created the home page and about page for mobile and desktop.
- Used a mobile-first approach to build the website and I also used a component-based design where I build the most important component to build another block of the website.
- Create the Featured section dynamically using Javascript.

### loom video link:
https://www.loom.com/share/392a02271af5458e8fd7d447e8b73eed

2022-03-10 22:55 UTC, nicupop729 requested changes
# STATUS: Required Changes ♻️

Hi @MohammedElseddik, 

Good job so far!
**Congratulations on your fabulous work** :champagne: :confetti_ball: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/iZKF7CKpEEva2OZE6a/giphy.gif)

### Some highlights for you
* Correct GitHubFlow practice ✔️ 
* Good commit messages ✔️ 
* Professional README ✔️ 
* Clean codebase ✔️ 

### Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-10 22:55 UTC, nicupop729 commented on README.md
> + Description of the project:
Every project should hold a descriptive title.

- [x] Kindly, ensure you have a title for your project in the README file.

2022-03-10 22:55 UTC, nicupop729 commented on README.md
> +https://mohammedelseddik.github.io/Web-Development-Capstone-Project/
This link leads me to a 404 Page not found.

- [ ] Please make sure that your deployment works as intended.
![image](https://user-images.githubusercontent.com/83596135/157761877-1ba2a2bf-bbd5-4061-affb-f703d4d290fb.png)

2022-03-10 22:55 UTC, nicupop729 commented on README.md
> +Feel free to check the [issues page](../../issues/).
Here we need to have a link to the issues page of our project. In the case of your project, the link is this one:
[issues page](https://github.com/MohammedElseddik/HTML-CSS-JavaScript-capstone-project/issues)

- [ ] Please take care of this aspect, implementing the right link for issues.

2022-03-10 22:55 UTC, nicupop729 commented on README.md
> +
We should not jump over sections from the README template. Always we need to give clear instructions to users to clone our repo.

- [ ] Kindly, I ask you to implement back all the sections from the README template and provide clear instructions for cloning the repo.
The link to the README template is [here](https://github.com/microverseinc/readme-template).

2022-03-10 22:55 UTC, nicupop729 commented on About-Page/about.html
> +          <li class="nav__item active-item"><a href="#">Cantact Us</a></li>
A typo slipped in here.

- [ ] Please fix the typo from "Cantact Us"

2022-03-10 22:55 UTC, nicupop729 commented on About-Page/about.html
> +      <nav class="header-nav">
Order for our design to match the Behance design, for the top nav,

- [ ] Please reduce its height;
- [ ] Kindly change its colour to a darker shade;

Your design:
![image](https://user-images.githubusercontent.com/83596135/157765338-4ed29989-6a80-4e59-9013-5bd40cd996c2.png)
Behance design:
![image](https://user-images.githubusercontent.com/83596135/157765455-89b17c2d-d03f-432e-803a-18c77483bafc.png)

2022-03-10 22:55 UTC, nicupop729 commented on About-Page/about.html
> +    </section>
In the Behance design, on the About page, the partners (featured Speakers on your version) are not displayed.

- [ ] Please make sure to remove the partners from the About page.

Note: for the mobile version, please ensure to keep the partners (featured Speakers on your version).

2022-03-10 22:55 UTC, nicupop729 commented on About-Page/about.html
> +    <footer class="footer-section">
In the Behance design, for the About page, the background is a shade of black.

- [ ] Kindly, redesign your footer from the About page in order to have that shade of black that the Behance design is using.
Your footer:
![image](https://user-images.githubusercontent.com/83596135/157766336-b5b0e316-6079-4615-b3ab-0f2107a101ca.png)
Behance design:
![image](https://user-images.githubusercontent.com/83596135/157766430-e80118d1-53b3-44e5-9695-5f06d3cf71e9.png)

**Note:** for the mobile version, please ensure to keep the white background for both Home and About pages.

2022-03-10 22:55 UTC, nicupop729 commented on css/home.css
> +    font-size: 2.3rem;
As this is a paragraph, the font size seems to be a little too big.

- [ ] Let's make sure we stick to the design and rescale this description.

2022-03-10 22:55 UTC, nicupop729 commented on css/about.css
> +    font-size: 2.2rem;
As this description is a paragraph and we want to match the design as close as possible, it looks like it is a little to big.

- [ ] Please downsize the font for this paragraph to match the Behance design

2022-03-11 10:49 UTC, Amrhub approved these changes
# Approved 💯 ✅ 🥳 🎈 🎉 

Hi @MohammedElseddik, 👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif)

## Highlights ✅ 
Highly organized and clean code ✔️ 👨🏻‍💻 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-11 11:45 UTC, merged